-- drop table comments;
-- drop table bookings;
-- drop table items;
-- drop table users;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
    );

create table if not exists requests
(
    id int not null primary key,
    description VARCHAR(255),
    requestor_id int references users(id),
    created TIMESTAMP WITHOUT TIME ZONE not null
);

create table if not exists items
(
    id int not null primary key,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(512) NOT NULL,
    is_available boolean,
    owner_id int references users(id),
    requests_id int references requests(id)
);

create table if not exists bookings (
    id int not null primary key,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date TIMESTAMP WITHOUT TIME ZONE,
    item_id int references items(id),
    booker_id int references users(id),
    status VARCHAR(255)
);

create table if not exists comments
(
    id int not null primary key,
    text VARCHAR(255),
    item_id int references items(id),
    author_id int references users(id),
    created TIMESTAMP WITHOUT TIME ZONE not null
);


